id: PFB439426
initial_creation_type: input
source_metadata:
  title: Drukpa Kunley Series
  language: en
  description: 'Texts by and about the controversial yogi and self-proclaimed ''madman''
    Drukpa Kunga Lekpa (''brug pa kun dga'' legs pa, 1455–1529), popularly known as
    Drukpa Kunley:'
  volume:
    a7f3385a8f6a43f2bb5a2171775921a1:
      title: Prayer to Drukpa Kunley
      parent: Prayers
created_at: '2022-02-28T23:05:39.878256'
last_modified_at: '2022-02-28T23:05:39.878263'
